### ISSUE TITLE
How to run server and and client(primary & secondary) in two different pc?

### ISSUE THREAD

**Issue by koruthu** [uptane/obsolete-reference-implementation#174]
I want to run image repository, director repository, Timeserver, primary and secondary in different different system; how can I do that?
could you help me?

**Comment by JustinCappos** [comment]
Sure, you're free to do this.  In fact, we do this when we run our demos.

What problem are you having when setting this up?

**Comment by awwad** [comment]
Please look through `demo/__init__.py` for the configuration values (IP, etc.) to run the demo on multiple systems and see if it works intuitively for you.  If you run into issues, please let us know.

**Comment by koruthu** [comment]
Hi Awwad,
Thanks for your solution.
I would like to update primary itself as the same way we are updating secondary. Is there way  to assign image for primary and and update primary itself?

**Comment by awwad** [comment]
In the current version of the reference implementation, the code in primary.py and demo_primary.py provides the code to handle acquisition, verification, and distribution of metadata and images, and the code in secondary.py and demo_secondary.py provides the code to handle verification for individual ECUs.  Your Primary should run both in order to both serve as a distribution hub and update itself.  In a later version of the reference implementation, I'll reorganize the code so that Primaries don't need to use the code in secondary.py, since this is inconvenient.

Please note that the purpose of the demonstration code (in `demo/`), is to provide a model of how to write your own code that uses the reference implementation to do whatever you need to do.
